version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: indian-law-rag-api
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./faiss_index:/app/faiss_index
      - ./.env:/app/.env

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: indian-law-rag-ui
    ports:
      - "8502:8501"
    environment:
      - API_URL=http://api:8000
